# Generated by Django 5.0.1 on 2024-05-04 03:12


from django.db import migrations

from payments.seed import create_data


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
