# Generated by Django 5.0.1 on 2024-09-14 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_filler_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userplan',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='userplan',
            old_name='startDate',
            new_name='start_date',
        ),
    ]
