# Generated by Django 5.0.1 on 2024-09-14 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_rename_enddate_userplan_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userplan',
            old_name='state',
            new_name='active',
        ),
    ]
