# Generated by Django 5.0.1 on 2024-04-21 05:45

import core.models.CustomValidations
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('idPersonality', models.AutoField(db_column='id_personality', primary_key=True, serialize=False)),
                ('tag', models.CharField(db_column='tag', max_length=10, validators=[core.models.CustomValidations.validate_is_string])),
                ('mind', models.DecimalField(db_column='mind', decimal_places=2, max_digits=3)),
                ('energy', models.DecimalField(db_column='energy', decimal_places=2, max_digits=3)),
                ('nature', models.DecimalField(db_column='nature', decimal_places=2, max_digits=3)),
                ('tactics', models.DecimalField(db_column='tactics', decimal_places=2, max_digits=3)),
                ('identity', models.DecimalField(db_column='identity', decimal_places=2, max_digits=3)),
                ('createdOn', models.DateTimeField(db_column='created_on')),
                ('status', models.BooleanField(db_column='status')),
            ],
            options={
                'db_table': 'MAE_PERSONALITY',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUser', models.AutoField(db_column='id_user', primary_key=True, serialize=False)),
                ('names', models.CharField(db_column='names', max_length=255, validators=[core.models.CustomValidations.validate_is_string])),
                ('lastnames', models.CharField(db_column='lastnames', max_length=255, validators=[core.models.CustomValidations.validate_is_string])),
                ('genre', models.CharField(db_column='genre', max_length=50, validators=[core.models.CustomValidations.validate_is_string])),
                ('birthdate', models.DateTimeField(db_column='birthdate', validators=[core.models.CustomValidations.validate_born_date])),
                ('image', models.ImageField(blank=True, db_column='image', null=True, upload_to='files/img/usuario')),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('email', models.EmailField(db_column='email', max_length=254, unique=True)),
                ('password', models.CharField(db_column='password', max_length=255)),
                ('degree', models.CharField(blank=True, db_column='degree', max_length=255, null=True)),
                ('university', models.CharField(blank=True, db_column='university', max_length=255, null=True)),
                ('budgetMin', models.DecimalField(db_column='budget_min', decimal_places=2, max_digits=3)),
                ('budgetMax', models.DecimalField(db_column='budget_max', decimal_places=2, max_digits=3)),
                ('district', models.CharField(db_column='district', max_length=255)),
                ('habits', models.CharField(blank=True, db_column='habits', max_length=255, null=True)),
                ('lastLogin', models.DateTimeField(blank=True, db_column='last_login', null=True)),
                ('status', models.BooleanField(db_column='status')),
                ('selfPersonality', models.ForeignKey(db_column='id_self_personality', on_delete=django.db.models.deletion.CASCADE, related_name='self_personality', to='core.personality')),
                ('targetPersonality', models.ForeignKey(blank=True, db_column='id_target_personality', on_delete=django.db.models.deletion.CASCADE, related_name='target_personality', to='core.personality')),
            ],
            options={
                'db_table': 'MAE_USER',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('idMatch', models.AutoField(db_column='id_match', primary_key=True, serialize=False)),
                ('flagMatch', models.BooleanField(db_column='flag_match')),
                ('flagDismatch', models.BooleanField(db_column='flag_dismatch')),
                ('status', models.BooleanField(db_column='status')),
                ('userReciever', models.ForeignKey(db_column='id_user_reciever', on_delete=django.db.models.deletion.CASCADE, related_name='user_reciever', to='core.user')),
                ('userSender', models.ForeignKey(db_column='id_user_sender', on_delete=django.db.models.deletion.CASCADE, related_name='user_sender', to='core.user')),
            ],
            options={
                'db_table': 'MAE_MATCH',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('idContact', models.AutoField(db_column='id_contact', primary_key=True, serialize=False)),
                ('type', models.CharField(db_column='type', max_length=50)),
                ('description', models.CharField(db_column='description', max_length=255)),
                ('status', models.BooleanField(db_column='status')),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'db_table': 'MAE_CONTACT',
            },
        ),
    ]
