# Generated by Django 5.0.1 on 2024-05-04 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='budget_max',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='budget_min',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
