# Generated by Django 5.0.1 on 2024-05-04 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_budget_max_alter_user_budget_min'),
        ('studies', '0003_degree_universities'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='degree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studies.degree'),
        ),
    ]
