# Generated by Django 5.0.1 on 2024-05-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_degree'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=10)),
                ('mind', models.DecimalField(decimal_places=2, max_digits=3)),
                ('energy', models.DecimalField(decimal_places=2, max_digits=3)),
                ('nature', models.DecimalField(decimal_places=2, max_digits=3)),
                ('tactics', models.DecimalField(decimal_places=2, max_digits=3)),
                ('identity', models.DecimalField(decimal_places=2, max_digits=3)),
                ('register_date', models.DateField()),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'db_table': 'personalities',
            },
        ),
    ]
