# Generated by Django 5.0.1 on 2024-05-04 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_personality'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='self_personality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='self_personality', to='accounts.personality'),
        ),
        migrations.AddField(
            model_name='user',
            name='target_personality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_personality', to='accounts.personality'),
        ),
    ]
