# Generated by Django 5.0.1 on 2024-05-12 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_self_personality_user_target_personality'),
        ('studies', '0003_degree_universities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studies.degree'),
        ),
    ]
