# Generated by Django 5.0.1 on 2024-06-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='habits',
            field=models.TextField(blank=True, null=True),
        ),
    ]
