# Generated by Django 5.0.1 on 2024-05-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0002_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
