# Generated by Django 5.0.1 on 2024-05-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0003_alter_match_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='flag_dismatch',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='flag_match',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, verbose_name='active'),
        ),
    ]
