# Generated by Django 5.0.1 on 2024-05-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0004_alter_match_flag_dismatch_alter_match_flag_match_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='active'),
        ),
    ]
