# Generated by Django 5.0.1 on 2024-05-12 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0005_alter_match_is_active'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='match',
            table='matches',
        ),
    ]
