# Generated by Django 5.0.1 on 2024-09-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0007_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='register_date',
            field=models.DateTimeField(null=True),
        ),
    ]
