# Generated by Django 5.0.1 on 2024-05-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'degrees',
            },
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
