# Generated by Django 5.0.1 on 2024-05-04 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_degree_alter_university_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='universities',
            field=models.ManyToManyField(related_name='universities', to='studies.university'),
        ),
    ]
