# Generated by Django 3.1.7 on 2022-05-19 14:30

from django.db import migrations

from locations.seed import create_data


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
